sudo: false
language: php
php:
#  - "7.0"
  - "5.6"
  - "5.5"
install:
  - composer self-update
  - composer install
script:
  - find . -type d \( -path ./vendor -o -path ./test \) -prune -o -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
#  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=vendor,test,config,data,autoload_classmap.php --extensions=php ./
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'
