<?php
$ratio = $this->instanceConfig['aspectRatio'];
$videoUrl = "https://player.vimeo.com/video/{$this->instanceConfig['videoId']}";
$query = [];

if (!empty($this->instanceConfig['autoPlay'])) {
    $query[$this->instanceConfig['autoPlay']] = '1';
}
if(!empty($query)) {
    $videoUrl = $videoUrl . '?' . http_build_query($query);
}

?>
<div class="rcm-vimeo">
    <div class="rcm-vimeo-video">
        <?php if ($this->instanceConfig['downloadLink']) : ?>
            <a href="<?= $this->instanceConfig['downloadLink'] ?>" target="_blank">Download Video</a>
        <?php endif ?>
        <div class='embed-container' rcm-vimeo-aspect-ratio="<?= $ratio; ?>">
            <iframe rcm-vimeo-aspect-ratio="<?= $ratio; ?>"
                    src='<?= $videoUrl; ?>'
                    frameborder='0'
                    webkitAllowFullScreen
                    mozallowfullscreen
                    allowFullScreen></iframe>
        </div>
        <div class='embed-container placeholder' rcm-vimeo-aspect-ratio="<?= $ratio; ?>">
            <div class="icon">&nbsp;</div>
            <div class="label">
                <a href="https://vimeo.com/<?= $this->instanceConfig['videoId'] ?>" target="_blank">
                    https://vimeo.com/<?= $this->instanceConfig['videoId'] ?>
                </a>
            </div>
        </div>
    </div>
</div>
