<?php
$ratio = $this->instanceConfig['aspectRatio'];
$videoId = $this->instanceConfig['videoId'];
$videoUrl = "https://player.vimeo.com/video/{$videoId}";
$downloadLinkType = $this->instanceConfig['downloadLinkType'];
$downloadWidth = (int)$this->instanceConfig['downloadWidth'];
$downloadLink = '';
$autoPlay = $this->instanceConfig['autoPlay'];
$overlayLink = '';

switch ($autoPlay) {
    case 'background' :
        $overlayLink = trim($this->instanceConfig['overlayLink']);;
        break;
    default:
        $overlayLink = '';
        break;
}

switch ($downloadLinkType) {
    case 'custom' :
        $downloadLink = $this->instanceConfig['downloadLink'];
        break;
    case 'vimeo-api':
        $downloadLink = '/vimeo/video/{videoId}/download';

        if (!empty($downloadWidth)) {
            $downloadLink = "{$downloadLink}?width={$downloadWidth}";
        }
        break;
    default:
        $downloadLink = '';
        break;
}

$downloadLink = str_replace('{videoId}', $videoId, $downloadLink);

$query = [];

if (!empty($autoPlay)) {
    $query[$autoPlay] = '1';
}
if (!empty($query)) {
    $videoUrl = $videoUrl . '?' . http_build_query($query);
}

$downloadLinkStyle = (empty($downloadLink) ? 'display: none;' : '');

$overlayLinkTag = '';
if (!empty($overlayLink)) {
    $overlayLinkTag
        = '
        <div class="rcm-vimeo-overlay" style="position: relative; width=100%;">
            <a href="' . $overlayLink . '" 
            style="display: block; position: relative; top: 0; left:0; width=100%;"
            rcm-vimeo-aspect-ratio="' . $ratio . '"
            > 
            </a>
        </div>
        ';
}

?>

<div class="rcm-vimeo">
    <div class="rcm-vimeo-video">
        <a class="rcm-vimeo-video-download"
           style="<?= $downloadLinkStyle ?>"
           href="<?= $downloadLink ?>"
           rel="nofollow"
           target="_blank"><?= $this->translate('Download Video') ?></a>
        <script>
            //Hide download links from crawlers to help avoid going over Vimeo's API rate limit
            document.getElementById('rcm-vimeo-a-tag-<?= $this->instanceId; ?>').href
                = '<?= substr($downloadLink, 0, 10) ?>' + '<?= substr($downloadLink, 10) ?>';
        </script>
        <div class='embed-container' rcm-vimeo-aspect-ratio="<?= $ratio; ?>">
            <iframe rcm-vimeo-aspect-ratio="<?= $ratio; ?>"
                    src='<?= $videoUrl; ?>'
                    frameborder='0'
                    webkitAllowFullScreen
                    mozallowfullscreen
                    allowFullScreen></iframe>
            <?= $overlayLinkTag ?>
        </div>
        <div class='embed-container placeholder' rcm-vimeo-aspect-ratio="<?= $ratio; ?>">
            <div class="icon">&nbsp;</div>
            <div class="label">
                <a href="https://vimeo.com/<?= $videoId ?>" target="_blank">
                    https://vimeo.com/<?= $videoId ?>
                </a>
            </div>
        </div>
    </div>
</div>

