<div class="htmlArea">
<?=
$this->rcmRichEdit(
    'html',
    '<iframe src="https://player.vimeo.com/video/140246494" xwidth="500" xheight="213" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    <p>
    <button href="https://vimeo.com/140246494/download?t=1450109484&amp;v=419005396&amp;s=4f3c358443797204a35c8a1709389eb4458c8e7a92e89c7d938f81d2e0042e0e" download="don\'t_just_live._reliv._1920x818.mp4" >Download</button>
    </p>',
    'div',
    []
); ?>
</div>
